### ISSUE TITLE
 Android log templates?

### ISSUE THREAD

**Issue by ChuXin30** [IntelligentDDS/SwissLog#2]

**Comment by ChuXin30** [comment]
I want to parse Android logs correctly, can you provide Android log templates?

**Comment by humanlee1011** [comment]
@ChuXin30 
The same question we have encountered. The goal here is to evaluate the effectiveness of the proposed log parser in large datasets. In this paper, we use Loghub dataset including Android logs to evaluate our log parser. You can find the Android log templates in this [link]( https://github.com/logpai/logparser/tree/master/logs/Andriod) and the full Android log [here](https://github.com/logpai/loghub/tree/master/Andriod). Although the file `Andriod_2k.log_templates.csv` contains 2k log samples, the templates can extend to the full dataset. We labelled logs matching in `Android_2k.log_templates.csv` with corresponding EventID and dropped the unmatched.  Then you can use the labelled one to finish evaluation.

**Comment by ChuXin30** [comment]
I understand, thank you very much
