### ISSUE TITLE
Supervised or self-supervised?

### ISSUE THREAD

**Issue by hayhan** [IntelligentDDS/SwissLog#3]
Thank you for your good work. It looks SwissLog is a method of supervised learning. Pls correct me if I'm wrong.

**Comment by humanlee1011** [comment]
Hi @hayhan ,

The log parsing part of SwissLog is an unsupervised framework and the anomaly detection part of SwissLog requires some labelled data to train the Attn-based Bi-LSTM model. The anomaly detection part is a method of supervised learning.

**Comment by hayhan** [comment]
Got it. Thank you for your prompt response.
