### ISSUE TITLE
Parameter extraction

### ISSUE THREAD

**Issue by razvangabrielc** [IntelligentDDS/SwissLog#4]
Hello, thank you for publishing the code of your paper. I played around with the code, and I was wondering if there is a way for extracting the parameters from the loglines? As for now I can see the code is only matching a logline to a template, but it does not extract the parameters. Thank you in advance!

**Comment by humanlee1011** [comment]
> 

Thanks for your attention! I forgot to add the parameter extraction part in our codes. But you can refer to the LogPAI work, our codes follow their log parsing framework. So you can implement the parameter extraction part following here: https://github.com/logpai/logparser/blob/7eb18dcb04d211940ba489ac0510004f523b9130/logparser/AEL/AEL.py#LL222C5-L222C5.

I will also update the parameter extraction part soon.  Thanks!

**Comment by humanlee1011** [comment]
> Hello, thank you for publishing the code of your paper. I played around with the code, and I was wondering if there is a way for extracting the parameters from the loglines? As for now I can see the code is only matching a logline to a template, but it does not extract the parameters. Thank you in advance!

Hi, sorry for the late update! I've already updated the parameter extraction part. Please kindly check the latest version :)
